# Generated by Django 5.1.3 on 2024-11-17 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('image_id', models.TextField(primary_key=True, serialize=False)),
                ('image', models.BinaryField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('localization', models.CharField(choices=[('ear', 'Ear'), ('face', 'Face'), ('neck', 'Neck'), ('scalp', 'Scalp'), ('abdomen', 'Abdomen'), ('back', 'Back'), ('chest', 'Chest'), ('trunk', 'Trunk - Other'), ('acral', 'Acral (Fingers/Toes)'), ('hand', 'Hand'), ('upper_extremity', 'Upper Extremity (Arm)'), ('foot', 'Foot'), ('lower_extremity', 'Lower Extremity (Leg)'), ('genital', 'Genital Area')], max_length=15)),
                ('lesion_type', models.CharField(choices=[('nv', 'Melanocytic nevi'), ('bkl', 'Benign keratosis-like lesions'), ('df', 'Dermatofibroma'), ('vasc', 'Vascular lesions'), ('mel', 'Melanoma'), ('bcc', 'Basal cell carcinoma'), ('akiec', 'Actinic keratoses and intraepithelial carcinoma')], max_length=5)),
            ],
            options={
                'db_table': 'images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.IntegerField()),
                ('version', models.CharField(max_length=50, unique=True)),
                ('weights', models.BinaryField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=10)),
            ],
            options={
                'db_table': 'model',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.TextField()),
                ('age', models.IntegerField()),
                ('session', models.TextField(blank=True, null=True)),
                ('session_exp', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.IntegerField()),
                ('probability', models.IntegerField(blank=True, null=True)),
                ('image', models.BinaryField()),
                ('localization', models.CharField(choices=[('ear', 'Ear'), ('face', 'Face'), ('neck', 'Neck'), ('scalp', 'Scalp'), ('abdomen', 'Abdomen'), ('back', 'Back'), ('chest', 'Chest'), ('trunk', 'Trunk - Other'), ('acral', 'Acral (Fingers/Toes)'), ('hand', 'Hand'), ('upper_extremity', 'Upper Extremity (Arm)'), ('foot', 'Foot'), ('lower_extremity', 'Lower Extremity (Leg)'), ('genital', 'Genital Area')], max_length=15)),
                ('lesion_type', models.CharField(choices=[('nv', 'Melanocytic nevi'), ('bkl', 'Benign keratosis-like lesions'), ('df', 'Dermatofibroma'), ('vasc', 'Vascular lesions'), ('mel', 'Melanoma'), ('bcc', 'Basal cell carcinoma'), ('akiec', 'Actinic keratoses and intraepithelial carcinoma')], max_length=5)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.model', to_field='version')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.users')),
            ],
            options={
                'db_table': 'requests',
                'managed': True,
            },
        ),
    ]
