# Generated by Django 5.1.3 on 2024-11-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="activation_function",
            field=models.CharField(
                choices=[
                    ("relu", "ReLU"),
                    ("sigmoid", "Sigmoid"),
                    ("softmax", "Softmax"),
                    ("tanh", "Tanh"),
                    ("elu", "ELU"),
                    ("selu", "SELU"),
                    ("linear", "Linear"),
                ],
                default="softmax",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="batch_size",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="model",
            name="dense_units",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="model",
            name="dropout_rate",
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name="model",
            name="epochs",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="model",
            name="input_shape",
            field=models.CharField(default="(28, 28, 3)", max_length=20),
        ),
        migrations.AddField(
            model_name="model",
            name="kernel_size",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="model",
            name="loss_function",
            field=models.CharField(
                choices=[
                    (
                        "sparse_categorical_crossentropy",
                        "Sparse Categorical Crossentropy",
                    ),
                    ("categorical_crossentropy", "Categorical Crossentropy"),
                    ("binary_crossentropy", "Binary Crossentropy"),
                    ("mean_squared_error", "Mean Squared Error"),
                    ("mean_absolute_error", "Mean Absolute Error"),
                    ("huber_loss", "Huber Loss"),
                    ("hinge", "Hinge"),
                    ("kl_divergence", "Kullback-Leibler Divergence"),
                ],
                default="sparse_categorical_crossentropy",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="metrics",
            field=models.CharField(
                choices=[
                    ("accuracy", "Accuracy"),
                    ("categorical_accuracy", "Categorical Accuracy"),
                    ("sparse_categorical_accuracy", "Sparse Categorical Accuracy"),
                    ("AUC", "AUC"),
                    ("Precision", "Precision"),
                    ("Recall", "Recall"),
                    ("mean_squared_error", "Mean Squared Error"),
                    ("mean_absolute_error", "Mean Absolute Error"),
                    (
                        "mean_absolute_percentage_error",
                        "Mean Absolute Percentage Error",
                    ),
                    ("top_k_categorical_accuracy", "Top K Categorical Accuracy"),
                ],
                default="accuracy",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="num_filters",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="model",
            name="optimizer",
            field=models.CharField(
                choices=[
                    ("sgd", "Stochastic Gradient Descent"),
                    ("adam", "Adam"),
                    ("rmsprop", "RMSprop"),
                    ("adagrad", "Adagrad"),
                    ("adadelta", "Adadelta"),
                    ("adamax", "Adamax"),
                    ("nadam", "Nadam"),
                ],
                default="adam",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="pool_size",
            field=models.IntegerField(default=2),
        ),
    ]
