# Generated by Django 5.1.3 on 2024-11-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="created_at",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
