# Generated by Django 5.1.3 on 2024-11-21 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_model_activation_function_model_batch_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model",
            name="activation_function",
        ),
        migrations.RemoveField(
            model_name="model",
            name="batch_size",
        ),
        migrations.RemoveField(
            model_name="model",
            name="dense_units",
        ),
        migrations.RemoveField(
            model_name="model",
            name="dropout_rate",
        ),
        migrations.RemoveField(
            model_name="model",
            name="epochs",
        ),
        migrations.RemoveField(
            model_name="model",
            name="input_shape",
        ),
        migrations.RemoveField(
            model_name="model",
            name="kernel_size",
        ),
        migrations.RemoveField(
            model_name="model",
            name="loss_function",
        ),
        migrations.RemoveField(
            model_name="model",
            name="metrics",
        ),
        migrations.RemoveField(
            model_name="model",
            name="model_id",
        ),
        migrations.RemoveField(
            model_name="model",
            name="num_filters",
        ),
        migrations.RemoveField(
            model_name="model",
            name="optimizer",
        ),
        migrations.RemoveField(
            model_name="model",
            name="pool_size",
        ),
        migrations.RemoveField(
            model_name="model",
            name="status",
        ),
        migrations.AddField(
            model_name="model",
            name="hyperparameters",
            field=models.TextField(default="default"),
        ),
        migrations.AlterField(
            model_name="model",
            name="version",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="requests",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="application.model"
            ),
        ),
        migrations.CreateModel(
            name="ActiveModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.IntegerField()),
                (
                    "model",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.model",
                    ),
                ),
            ],
            options={
                "db_table": "model_active",
                "managed": True,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)),
                        name="single_active_model_constraint",
                    )
                ],
            },
        ),
    ]
