# Contributors:
# * Contributor: <alexandersafstrom@proton.me>
# * Contributor: <rokanas@student.chalmers.se>
# * Contributor: <arvinrahimi78@gmail.com>
# * Contributor: <arvinra@student.chalmers.se>
# * Contributor: <elindstr@student.chalmers.se>
# * Contributor: <kaisa.arumeel@gmail.com>
from .authentication import AuthenticationTests
from .models import ModelTests
from .add_data import AddDataTests
from .get_all_requests import GetAllRequestsTests
from .get_all_users import GetAllUsersTests
from .create_request import CreateRequestTests
from .ml import MLTests
from .retrain import RetrainTests
from .get_specific_request import GetSpecificRequestTests
from .get_requests_by_username import GetRequestsByUsernameTests
from .predictions import PreprocessDataTests
from .delete_user import DeleteUserTests
from .job_expiration import JobExpirationTests
from .get_total_datapoints import GetTotalDataPointsTests
